#
## 开发环境配置
#server:
#  # 服务器的HTTP端口，默认为80
#  port: 8081
#  servlet:
#    # 应用的访问路径
#    context-path: /mock
#  tomcat:
#    # tomcat的URI编码
#    uri-encoding: UTF-8
#    # 连接数满后的排队数，默认为100
#    accept-count: 1000
#    threads:
#      # tomcat最大线程数，默认为200
#      max: 800
#      # Tomcat启动初始化的线程数，默认值10
#      min-spare: 100

## 日志配置
#logging:
#  level:
#    work.skymoyo: debug
#    org.springframework: warn

## 用户配置
#user:
#  password:
#    # 密码错误{maxRetryCount}次锁定10分钟
#    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html #模板后缀
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
